config/routes.rb
Rails.application.routes.draw do
    get 'top/main'
    post 'top/login' => 'top#login'
    get 'top/logout'
    root 'top#main'
     resources :users
     resources :tweets
     resources :likes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes
    has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :likes
    has_many :like_tweets, through: :likes, source: :tweet
    validates :uid, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    user = User.find_by(uid: session[:login_uid])
    user.like_tweets << tweet
    redirect_to root_path
  end
  def destroy
    tweet = Tweet.find(params[:id])
    user = User.find_by(uid: session[:login_uid])
    tweet.likes.find_by(user_id: user.id).destroy
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
      @tweets = Tweet.all
    end
    def login
       user = User.find_by(uid: params[:uid])
        if user and BCrypt::Password.new(user.pass) == params[:pass]
            session[:login_uid] = params[:uid]
            redirect_to root_path
        else
            render "login_form"
        end
    end 
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
  @tweets = Tweet.all
  end
  def new
   @tweet = Tweet.new
  end
  def create
    @tweet = Tweet.new(message: params[:tweet][:message])
    if @tweet.save
      flash[:notice] = '1レコード追加しました'
      redirect_to root_path
    else
      render 'new'
    end
  end
  def destroy
  tweet = Tweet.find(params[:id])
   tweet.destroy
        redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def new
        @user = User.new
    end
    def create
        uid =  params[:user][:uid]
        pass = BCrypt::Password.create( params[:user][:pass])
        profile = params[:user][:profile]
        @user = User.new(uid: uid,pass: pass, profile: profile)
        if @user.save
            redirect_to controller: :users, action: :index
        else
            render 'new'
        end
    end
    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to controller: :users, action: :index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if session[:login_uid] %>
    ログインしています
    <% else %>
    ログインしていません
    <% end %>
  </body>
</html>

app/views/top/login_failed.html.erb
ログイン失敗
<%= link_to '戻る', :back %>

app/views/top/login_form.html.erb
<%= form_tag '/top/login', method: :post do %>
<%= label_tag :uid, 'ユーザーID' %>
<%= text_field_tag :uid %>
<%= label_tag :pass, 'パスワード' %>
<%= password_field_tag :pass %>
<%= submit_tag 'ログイン' %>
<% end %>
<a href="/users">ユーザ一覧</a>

app/views/top/main.html.erb
<% if session[:login_uid] %>
<% @tweets.each do |e| %>
<%= e.message %>
<%= link_to 'いいね', likes_path(tweet_id: e.id), method: :post %>
<%= link_to 'いいね削除', like_path(e), method: :delete %>
<% if e.likes.count == 0 %>
<%= link_to '♡', likes_path(tweet_id: e.id), method: :post %>
<% else %>
<%= link_to '❤️️️', like_path(e), method: :delete %>
<% end %>
<%= link_to '削除', "/tweets/#{e.id}", method: :delete %>
<br>
<% end %>
<p><%= link_to 'ツイート', '/tweets/new' %></p>
<p><%= link_to 'ログアウト', top_logout_path %></p>
<% else %>
<% @tweets.each do |e| %>
<%= e.message %>
<br>
<% end %>
<p><%= link_to 'ログイン', '/top/login', method: :post %></p>
<% end %>

app/views/top/tmp.html.erb
ログインしていません
<p><%= link_to 'ログイン', {controller: "top", action: "login"}, method: :post  %></p>
<p><%= link_to 'ユーザ登録', '/users/new' %></p>
<a href="/users">ユーザ一覧</a>

app/views/tweets/index.html.erb
<% @tweets.each do |e| %>
<%= e.message %>
<%= link_to '削除', "/tweets/#{e.id}", method: :delete %>
<br>
<% end %>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
    <span style="color:red;">
        <h3>エラーがあります。</h3>
        <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </span>
<% end %>

<%= form_for @tweet, url: {action: :create} do |f| %>
    <%= f.label :message, 'ツイート' %>
    <%= f.text_field :message %>
    <%= f.submit 'ツイート' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= user.uid %>
    <%= user.pass %>
    <%= user.profile %>
    <br>
    <p>
    <%= link_to '削除', "/users/#{user.id}", method: :delete %>
    </p>
<% end %>
<%= link_to "ユーザ登録", "/users/new" %>
<%= link_to "メイン", "top/main" %>

app/views/users/new.html.erb
<% if @user.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>
<%= form_for @user , url: {action: :create} do |f| %>
<%= f.label :uid, 'ID' %>
<%= f.text_field :uid %>
<%= f.label :pass, 'パスワード' %>
<%= f.password_field :pass %>
<%= f.label :profile, 'プロフィール' %>
<%= f.text_field :profile %>
<%= f.submit '登録' %>
<% end %>